/*
 * Refer to the named.conf(5) and named(8) man pages, and the documentation
 * in /usr/share/doc/bind-* for more details.
 */

acl "xfer" {
	none;
};

acl "trusted" {
	127.0.0.0/8;
	192.168.0.0/24;
	192.168.10.0/24;
	10.128.0.0/14;
	172.30.0.0/16;
	::1/128;
};

options {
	directory "/var/bind";
	pid-file "/run/named/named.pid";

	listen-on-v6 { ::1; };
	listen-on { 127.0.0.1; 192.168.0.103; };

	allow-query {
		trusted;
	};

	allow-query-cache {
		trusted;
	};

	allow-recursion {
		trusted;
	};

	allow-transfer {
		none;
	};

	allow-update {
		none;
	};

	forward first;
	forwarders {
		77.91.63.250;
		1.1.1.1;
		8.8.8.8;
	};

	dnssec-validation no;
};

/*
logging {
	channel default_log {
		file "/var/log/named/named.log" versions 5 size 50M;
		print-time yes;
		print-severity yes;
		print-category yes;
	};

	category default { default_log; };
	category general { default_log; };
};
*/

include "/etc/bind/rndc.key";

controls {
	inet 127.0.0.1 port 953
		allow { 127.0.0.1/32; ::1/128; }
		keys { "rndc-key"; };
};

zone "." IN {
	type hint;
	file "/var/bind/named.cache";
};

zone "localhost" IN {
	type master;
	file "pri/localhost.zone";
	notify no;
};

//
// Główna domena
//
zone "stolarek.org.pl" {
	type master;
	file "/var/bind/pri/stolarek.org.pl.local.zone";
	allow-query { any; };
	allow-transfer { none; };
};

//
// OpenShift SNO #1
//
zone "sno.stolarek.org.pl" {
	type master;
	file "/var/bind/pri/sno.stolarek.org.pl.local.zone";
	allow-query { any; };
	allow-transfer { none; };
};

//
// OpenShift SNO #2
//
zone "sno2.stolarek.org.pl" {
	type master;
	file "/var/bind/pri/sno2.stolarek.org.pl.local.zone";
	allow-query { any; };
	allow-transfer { none; };
};

//
// Reverse DNS for ordinanry addresses
//
zone "0.168.192.in-addr.arpa" IN {
	type master;
	file "/var/bind/pri/stolarek.org.pl.reverse.zone";
};
//
// Reverse DNS for IMM Remote management modules of rack servers
//
zone "10.168.192.in-addr.arpa" {
    type master;
    file "/var/bind/pri/stolarek.imm.org.pl.reverse.zone";
};
