authoritative;
option subnet-mask 255.255.255.0;
subnet 192.168.0.0 netmask 255.255.255.0
{
	allow unknown-clients;
	allow booting;
	allow bootp;
	next-server 192.168.0.103;
	option routers 192.168.0.1;
	option domain-name-servers 192.168.0.103, 192.168.0.1, 8.8.8.8;
	option domain-name "stolarek.org.pl";
	interface enp0s26f1u1;
	log-facility local7;
	filename "pxelinux.0";
	        pool {
		     range 192.168.0.101 192.168.0.254;
		#SNO - ibm x3550 M4 nowy
		host sno{
			hardware ethernet 6C:AE:8B:55:77:25;
			fixed-address 192.168.0.214;
			option host-name "sno.sno.stolarek.org.pl";
		}
		#SNO2 - na HP DL360 g6
		host sno2{
			hardware ethernet d8:d3:85:b9:ac:72;
			fixed-address 192.168.0.215;
			option host-name "sno2.sno2.stolarek.org.pl";
		}
		#Dell 1u PowerEdge 1950 pod virt, nie da sie sno na nim
                host ovirt{
                        hardware ethernet 00:19:b9:ed:01:27;
                        fixed-address 192.168.0.220;
                        option host-name "ovirt.stolarek.org.pl";
                }
		#sno3 HP DL360 G6 dla Grzegorza
		host sno3{
                        hardware ethernet 98:4b:e1:73:5f:24;
                        fixed-address 192.168.0.216;
                        option host-name "sno3.sno3.stolarek.org.pl";
                }
		#workstacja Lenovo m51p, serwer dhs, dhcpd
		host lenovo-workstation{
			hardware ethernet 00:1a:6b:4e:38:2e;
			fixed-address 192.168.0.103;
			option host-name "lenovo-workstation";
                
		}
		#Mikrotik switch
		host mikrotik{
			hardware ethernet 04:f4:1c:7d:3b:c0;
			fixed-address 192.168.0.241;
			option host-name "mikrotik";
		}
		#IMM dla sno IBM x3550 M4 
		host sno-imm{
			hardware ethernet 6c:ae:8b:55:77:26;
			fixed-address 192.168.10.5;
			option host-name "imm";
		}
		#REGISTRY - stary HP DL360 G5
		host centos7{
			hardware ethernet 00:1f:29:09:2e:b4;
			fixed-address 192.168.0.116;
			option host-name "centos7";
		}
		#iLO od sno2 HP DL360 G6
                host ilo{
                        hardware ethernet d8:d3:85:c2:88:1c;
                        fixed-address 192.168.10.6;
                        option host-name "ilo";
                }
		#storage.stolarware.pl
		host storage.stolarware.pl{
			hardware ethernet 00:20:f2:00:bd:01;
			fixed-address 192.168.0.115;
			option host-name "storage";
		}
		#IMAC - stary mac przy biurku
                host imac.stolarware.pl{
                        hardware ethernet 00:16:cb:a0:7f:f9;
                        fixed-address 192.168.0.105;
                        option host-name "imac";
		}
}
}


